### PR TITLE
[WIP] Bot all-contributors

### PR DESCRIPTION
**Pull request by anamanica**
# Change Summary

## Overview
Added the all-contributors bot to the README.md similar to imap_processing.

## New Dependencies
None

## New Files
- .all-contributorsrc
   - Holds formatting code, and contributors information.

## Deleted Files
None

## Updated Files
- README.md
   - Added contributors section.

## Testing
None needed.

### CODE REVIEW

**Comment by anamanica** [comment]
@all-contributors please add @anamanica for doc

**Comment by anamanica** [comment]
I have got the bot working locally and I am able to take code from the `.all-contributorsc` file and have it transfer to the `README.md`, but as you can see, the bot isn't listening to the remote repo. Is there something else I should do?

**Comment by maxinelasp** [comment]
Did you configure the repo settings to add the bot? https://allcontributors.org/docs/en/bot/installation I'm not sure if you have permission or not, but I think you do

**Comment by anamanica** [comment]
https://github.com/all-contributors please add @anamanica for doc

**Comment by anamanica** [comment]
@maxinelasp, Just to answer your question, Greg said that he added the all-contributors bot to the repo, but I am still not getting it to work here (you can see my most recent comment below). Any thoughts?

**Comment by maxinelasp** [comment]
That link implies that you need to have the readme updated first, so maybe if you merge this it will work?
`If you prefer your contributors table in a place other than the README.md; After merging your first bot PR, you can move your contributors table, see files in the [bot configuration](https://allcontributors.org/docs/en/bot/configuration)`

**Review by maxinelasp — APPROVED** [review]
You're good to merge this and see if it fixes the issue you were having with running the bot on the repo. It looks good to me

**Comment by anamanica** [comment]
@all-contributors please add @anamanica for doc

**Comment by anamanica** [comment]
@maxinelasp That worked great! After I merged the branch and commented again, another PR was made from the bot to add me as a docs contributor. I went ahead and approved this myself and merged it to make sure everything works correctly!

**Pull request merged**
